spring:
  application:
    name: bincker
  datasource:
    url: jdbc:sqlite:database.db
    driver-class-name: org.sqlite.JDBC
  profiles:
    active: local
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted