#!/usr/bin/env bash
set -e
url="$1"
url_file="$HOME/.config/clash/subscribe.url"
service_name="clash-meta@$(id -un)"

function usage() {
    echo "usage:"
    echo "$0 <url>"
}

if [ -z "$url" ] && [ -f "$url_file" ]; then
    url="$(cat "$url_file")"
fi

if [ -z "$url" ]; then
    usage
    exit 1
fi

if ! command -v curl >/dev/null; then
    echo "curl not installed."
    exit 1
fi

curl -sL "$url" -o "$url_file"
if systemctl list-units | grep -q "$service_name"; then
    sudo systemctl restart "$service_name"
fi
