#!/usr/bin/env bash
set -e
url="$1"
url_file="/etc/mihomo/subscribe.url"
config_file="/etc/mihomo/config.yaml"
service_name="mihomo"

function usage() {
    echo "usage:"
    echo "$0 <url>"
}

if [ -z "$url" ] && [ -f "$url_file" ]; then
    url="$(cat "$url_file")"
fi

if [ -z "$url" ]; then
    usage
    exit 1
fi

if ! command -v curl >/dev/null; then
    echo "curl not installed."
    exit 1
fi

if ! sudo curl -sL "$url" -o "$config_file"; then
    echo "failed to download config from $url"
    exit 1
fi

echo "$url" | sudo tee "$url_file"
if systemctl list-units | grep -q "$service_name"; then
    sudo systemctl restart "$service_name"
fi
